### ISSUE TITLE
Iris by Lowe's WiFi plug

### ISSUE THREAD

**Issue by bob5731** [arcus-smart-home/arcusplatform#10]
Now that Iris has shut down. how do I setup my Iris by Lowe's WiFi plug?

**Comment by nicholasstudt** [comment]
The WiFi plug could be made to work by pulling up the Arcus platform and then pointing your plug at your instance of the platform.

**Comment by AndrewX192** [comment]
@nicholasstudt Are you sure it's possible to set the platform URL in the plug? I don't see any documentation or endpoints available that the app/sample code hits that suggest it can be configured.
