### ISSUE TITLE
Kafka does not start cleanly outside of runDocker

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#12]
It is not possible to start the system with `docker start` because eyeris-kafka does not come up cleanly. This results in the following class of errors within all the other containers:

`
W0410 01:29:49.447 ucer-1  o.a.kafka.clients.NetworkClient] Error while fetching metadata with correlation id 3815 : {platform=LEADER_NOT_AVAILABLE}
`

The temporary solution is to blow away eyeris-kafka each time instead of reusing the container.

**Comment by nicholasstudt** [comment]
This seems like something odd in the kafka instance that you are running, if the leader isn't available and there is only one node. 

Have not seen this before, but it might be related to the kafka thinking it's hostname or id is not the same on each run.

**Comment by AndrewX192** [comment]
Now that I know docker is the preferred deployment strategy, I'm going to keep looking into this.

**Comment by AndrewX192** [comment]
I'm going to close this - the current scripts are pretty fragile, but aren't suitable for production. arcus-k8 (arcus on kubernetes) is the best solution for deployment at this time.
