### ISSUE TITLE
Productionized setup instructions

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#13]
I've already gotten arcusplatform to run using gradle, e.g. in docker, but I'm unsure if this is how it was intended to run in production, as the processes within the container run as root and otherwise generally doesn't appear to be production ready (see #11 and #12 as potential examples)

**Comment by nicholasstudt** [comment]
Docker containers were deployed to a container service. This configuration was not included in the published source code as it is tightly coupled to the deployment environment. Containers configured as they currently are intended only for local environment testing and deployment.

That said, these containers are nearly identical to what was utilized in production with only configuration pieces overridden via either environment variables for the services or replacement/addition of configuration files specific to the environment by mounting external drives with the configuration files present.

**Comment by AndrewX192** [comment]
I just found 
```gradle
def addLocalProps(cLine) {
   def localPropsHome = System.env['LOCAL_PROPS_HOME']
   if (localPropsHome != null) {
      def localPropsPath = localPropsHome + '/' + project.name + '.properties'
      if (file(localPropsPath).exists()) {
         cLine.add('--env-file=' + localPropsPath);
      }
   }
}```

in gradle/container.gradle - that appears to have been the solution. I'll take a look at that in more detail.

**Comment by AndrewX192** [comment]
I have most of a solution in https://github.com/wl-net/arcus-k8, it's not entirely production (e.g. it runs cassandra with one instance, and there's still known gaps like the containers running as root)

**Comment by AndrewX192** [comment]
I'm closing this - if someone wants to setup Arcus, I would point them to arcus-k8 as the means to do it. It's not as efficient for small setups, but it should work reliably.
