### ISSUE TITLE
Adjust defaults for easier setup

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#14]
Currently the setup process is complicated by needing to setup the configuration for each service and detail (e.g. billing api credentials) in order to get the platform up. Since there will be more deployments of Arcus, the defaults should be changed so that reasonable defaults (e.g. billing is disabled) are in place, similar to how other settings (like CORS) are handled.

**Comment by nicholasstudt** [comment]
Defaults can be overridden with environmental variables allowing for deployments to individualize their setup. This was accomplished in marathon deployment descriptors in non local environments.

**Comment by AndrewX192** [comment]
Thanks for that detail. My understanding is that the configuration could only be set by using the properties files, but I'll look into configuration through environment variables.. I presume that logic would be somewhere in the bootstrap code. I was hoping there'd be a single properties file that got sourced, but I never found any logic that did that.

**Comment by AndrewX192** [comment]
I'm going to close this. The recommended deployment method is currently arcus-k8. Local development is rather challenging at the moment, but the work to fix that extends beyond defualts
