### ISSUE TITLE
Update older hubs?

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#19]
I got another hub for testing purposes, but I'm unsure how to update it now that the iris servers are gone. The hubdebug tools mention providing a firmware image, but that appears to be unavailable now.

**Comment by nicholasstudt** [comment]
This would require building a new hubOS firmware then instructing the hub to install the firmware using the oculus tool.

**Comment by AndrewX192** [comment]
Right, the challenge for me is how to create the new firmware image - I've read through quite a bit of the hub-client code and feel comfortable than within a few hours I could figure out how tell the hub to update, but i'm unclear on how to generate the bin files. For now it appears that I can overwrite jars in /data/agent/libs temporarily to test things (until a factory reset), but I can't update components like the kernel or operating system without updating the entire firmware.

**Comment by ihatemyisp** [comment]
@nicholasstudt Any change we could get some info on building the firmware?

**Comment by AndrewX192** [comment]
The hub is based on Yocto Linux, in theory with the meta-ti overlay, or simply the beaglebone machine target. I've been unable to build a kernel that boots on the IRIS IH-200 Hub, but I think it's certainly possible with more time.

It is not recommended to build uboot, since there seems to be some changes required in order to recover because booting over UART does not work.

**Comment by AndrewX192** [comment]
Closing for now - can replace with specific items once there's a general plan
