### ISSUE TITLE
Watch dog running

### ISSUE THREAD

**Issue by thegillion** [arcus-smart-home/arcusplatform#2]
When SSH into the hub the Watchdog with reboot the hub on a time out. I am trying to kill the watchdog but can't I will report back if I find out more.

**Comment by nicholasstudt** [comment]
Correct, the watchdog will force a hub reboot if it is unable to contact the platform and successfully connect. This is the intended behavior to force hubs to reconnect if they get into an unknown state. If you are attempting to use the hub as a general purpose computing platform you'll want to disable this watchdog.
