### ISSUE TITLE
ppa:wedupd8team/java is discontinued

### ISSUE THREAD

**Issue by TheEssemCraft** [arcus-smart-home/arcusplatform#27]
With the new Oracle Java license put into effect on April 16, 2019, the `webupd8team/java` PPA has been discontinued and no longer works. This is significant as the `:platform:arcus-khakis:distDocker
` Gradle task relies on this to complete. Maybe try switching to the `openjdk-8-jdk` package instead?

**Comment by AndrewX192** [comment]
Yes, you'll need to change that to install openjdk-8-jdk-headless, and comment out the JAVA_HOME and PATH changes in khakis/eyeris-java/Dockerfile. There should be a pull request up to fix this in the next few days. Interestingly, last night I also ran into an issue with the locale package following this change to java, but I'm unclear if it's related. I may need to follow up on this issue or create a new issue for that problem.

**Comment by AndrewX192** [comment]
See #30 for a fix.

**Comment by AndrewX192** [comment]
The fix has landed. Please advise if you are still experiencing difficulties, or close this issue.
