### ISSUE TITLE
Hold my hand please.. 

### ISSUE THREAD

**Issue by shanweitzel** [arcus-smart-home/arcusplatform#58]
Ok umm.. I have no idea how all this works.. I know, I know... how annoying, but I have this insatiable hobby of smart homing and I have all this iris stuff and it appears as if you guys are trying to rebuild a more workable platform for the iris products people spent their hard earned money on. But can somebody please please please just post how to begin.. how do I get this code onto the hub? You know, the iris hub... right? Do I connect the hub by usb to my computer and just run the code? Or does it do it wirelessly (probably not, right?).. and do I do it only through terminal from my Mac? Or is there a program like Code Runner that can do it so much easier? Am I supposed to be entering code in terminal to customize only the parts I need or is there a file I run and BAM it’s all good?

**Comment by AndrewX192** [comment]
The code for the hub is incomplete, thus you can't put Arcus on an Iris Hub. You can however run the Arcus Platform and have an Iris hub connect to it, to regain much of the existing functionality under Iris.

You should be able to run Arcus with gradle as mentioned in doc/, but it's a pain to configure. If you are familar with Kubernetes you should look at https://github.com/wl-net/arcus-k8 as a means to get Arcus up and running.

That said, developing new features and extending/maintaining Arcus is non-trivial. If you are simply looking to get existing Iris devices up with minimal fuss I'd recommend looking at Hubitat.

**Comment by AndrewX192** [comment]
Closing. Please use http://forum.livingwithiris.com/forum/62-arcus/ for support and general questions.
