### ISSUE TITLE
Upgrade gradle to 5.x

### ISSUE THREAD

**Issue by AndrewX192** [arcus-smart-home/arcusplatform#68]
Gradle 5 is available, and keeping up to date with newer gradle versions will be important in supporting modern java versions (9+) in the future. Unfortunately this upgrade is non-trivial due to Gradle shipping with a newer version of groovy that can't easily be upgraded to, due to argument/validation issues when importing drivers and their capability files.

**Comment by wjsturm** [comment]
Hello Andrew,

Been following all your contributions to Arcus.
I still haven't tried to connect my former Iris hub but have been focusing
on rebuilding my hardware network with Smart Things hub with new hardware,
i.e., cameras, switches, water sensors and etc.

So I have over a dozen Iris cameras, and many Iris security sensors for
windows and doors. Fortunately my 1/2 dozen thermostats transitioned to
Smart Things.

My question is: if I did connect my Iris V.2 hub to Arcus platform through
GitHub what devices will I be able to pair and function? Will the cameras
ever be part of the connected Arcus platform?

Thanks again for all your contributions.

Best regards,

Bill

**Comment by AndrewX192** [comment]
Please don't discuss unrelated new issues/questions in existing GitHub issues. The best place to discuss this would be in http://forum.livingwithiris.com/forum/62-arcus/. Currently the only supported devices are zigbee, zwave, and IPCD. The other protocols were not fully open sourced and are not supported at this time.

**Comment by AndrewX192** [comment]
Addressed in #89
